### ISSUE TITLE
Allow multiple authenticators to be used simultaneously

### ISSUE THREAD

**Issue by pcastellazzi** [prestosql/prestosql.io#101]
As of now you can only configure one password authenticator. I would like to be able to use at least two of them at the same time.

My use case for this is as follows, we have users on our ActiveDirectory account, which are allowed multiple things including access to presto, and we have what we call service accounts, which are user/pass combinations used for communication between services, this are rotated often and usually generated on demand. I would like to be able to configure LDAP as the default authentication mechanism with a fallback to FILE for this service accounts.

The thread about this issue on [slack](https://prestosaql.slack.com/archives/CFLB9AMBN/p1594922734257100)

**Comment by martint** [comment]
This github repository is for the prestosql.io website. Please re-submit this issue at http://github.com/prestosql/presto

**Comment by pcastellazzi** [comment]
Apologies, my bad.
