### ISSUE TITLE
Data skew optimization have no effect on view

### ISSUE THREAD

**Issue by blacklit** [prestosql/prestosql.io#57]
we are working on prestosql 322， and find the following problem:
when data skew in a group-by operation happens, presto hive can automatically optimize the Query Plan by add a stage to balance the load of the skew node; while if we query an VIEW, the optimization have not effect，if the issue can be improved by adjust the properties?

the following is the Tasks table of query:
**when query a hive table with SQL:**

select statTime,sum(uv) as uv from (select 201909 as statTime,distinct_id,1 as uv from event where ds between 20190901 and 20190930 group by 1,2) group by 1

![image](https://user-images.githubusercontent.com/45591761/69522178-bccb2980-0f9b-11ea-876c-483c78b7d096.png)

**when query a view with SQL:**
tips: the view is the union of hive table event and an empty kudu table.

select statTime,sum(uv) as uv from (select 201909 as statTime,distinct_id,1 as uv from event_vd where ds between 20190901 and 20190930 group by 1,2) group by 1

![image](https://user-images.githubusercontent.com/45591761/69522457-60b4d500-0f9c-11ea-9606-acebaaf6b71b.png)

**Comment by findepi** [comment]
Hi @blacklit!

 thanks for reporting this.

This repository is for the _website_ only, so let me close the issue.

Presto-related issues should be reported at https://github.com/prestosql/presto/issues/
However, in this case, I'd recommend starting a thread on the `#troubleshooting` channel on our slack (https://prestosql.io/slack.html)
See you there!
