### ISSUE TITLE
prestosql查询es

### ISSUE THREAD

**Issue by myDemoMike** [prestosql/prestosql.io#82]
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('}' (code 125)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@737fb8ac; line: 13, column: 10]"}},"status":400}

当ES中有字段类型为Array类型时，
按照官方https://prestosql.io/docs/current/connector/elasticsearch.html#array-types
使用presto终端执行会出现如上的错误。遇到这种情况怎么处理

**Comment by findepi** [comment]
@myDemoMike this repository is for https://prestosql.io/ website only.
The repository for the Presto project is at: https://github.com/prestosql/presto

For a troubleshooting question like this please join the `#troubleshooting` channel on [our Slack](https://prestosql.io/slack.html).
See you there!
